openapi: '3.0.0'
# modularized based off: https://github.com/OAI/OpenAPI-Specification/issues/1961
info:
  version: 1.0.0
  title: Sotheby's Shipment
  description: The official v1 Shipment API
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /v1
paths:
  /shipments:
    $ref: './shipments/shipments.yml#/shipments'
  /shipments/quote:
    $ref: './shipments/shipmentsQuote.yml#/shipmentsQuote'
  /shipments/id/{shipment_id}:
    $ref: './shipments/shipmentsById.yml#/shipmentsById'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key